# Site settings
title: mntn.dev
author:
  name: Thomas Gorham
  email: tgiv014@gmail.com

description: >- # this means to ignore newlines until "baseurl:"
  The personal blog of Thomas Gorham,
  Hardware & Software Engineer

show_excerpts: false

minima:
  social_links:
    twitter: TGorhamIV
    github:  tgiv014
    linkedin: thomas-gorham
    
# Build settings
markdown: kramdown
remote_theme: tgiv014/minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
